export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Product } from "./Product";
export { default as Products } from "./Products";
export { default as Signup } from "./Signup";
export { default as Purchases } from "./Purchases";
export { default as Cart } from "./Cart";
export { default as PurchaseData } from "./PurchaseData";
export { default as User } from "./User";
export { default as AddProduct } from "./AddProduct";
export { default as AddCategory } from "./AddCategory";
export { default as Category } from "./Category";
export { default as Search } from "./Search";
export { default as P404 } from "./P404";
export { UpdateProduct } from "./UpdateProduct";
